coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 50%
        base: auto

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "core/src/main/scala/org/bitlap/tools/package.scala"
  - "core/src/main/scala/org/bitlap/tools/macros/macros.scala"
  - "cacheable/src/main/scala/org/bitlap/tools/cacheable/LogUtils.scala"
  - "cacheable/src/main/scala/org/bitlap/tools/cacheable/ZRedisConfiguration.scala"
  - "cacheable/src/main/scala/org/bitlap/tools/cacheable/ZRedisLive.scala"
  - "cacheable/src/main/scala/org/bitlap/tools/cacheable/ZRedisService.scala"
