coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
#    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "src/main/scala/io/github/dreamylost/package.scala"
  - "src/main/scala/io/github/dreamylost/macros/macros.scala"