pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^scala-steward$
      - check-success=Github CI - Pull Request
    actions:
      merge:
        method: merge