name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish Local
        run: sbt +publishLocal

      - name: Build
        run: sbt +compile

      - name: Run Test
        run: sbt test

      - name: Test with Coverage / Static code analyse / Code style
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sbt \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=gastonschabas \
          -Dsonar.projectKey=jxnu-liguobin_scala-macro-tools \
          -Dsonar.sources=src/main/scala \
          -Dsonar.tests=src/test/scala \
          -Dsonar.scala.coverage.reportPaths=target/scala-2.13/scoverage-report/scoverage.xml \
          clean compile coverage test coverageReport sonarScan